// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA82Q522MlSXJ36x9ZsUEf2KPN16ibnP-s',
    appId: '1:15157883302:android:f8dadf1d66543de2e61f67',
    messagingSenderId: '15157883302',
    projectId: 'chatapp-d3786',
    storageBucket: 'chatapp-d3786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-os84YZWxrrsXkNvtcbsBF2N8Rg0p51A',
    appId: '1:15157883302:ios:753c540b1b448da1e61f67',
    messagingSenderId: '15157883302',
    projectId: 'chatapp-d3786',
    storageBucket: 'chatapp-d3786.firebasestorage.app',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoH5xLzUnPdfuC1kguGOowGRsw-x2ItWU',
    appId: '1:15157883302:web:2c4a43771995d85be61f67',
    messagingSenderId: '15157883302',
    projectId: 'chatapp-d3786',
    authDomain: 'chatapp-d3786.firebaseapp.com',
    storageBucket: 'chatapp-d3786.firebasestorage.app',
    measurementId: 'G-C2TZC44FL2',
  );

}